#!/bin/bash
echo
echo Please chose one of the options below
echo
echo 'a = display date and time'
echo 'b = list files and directories'
echo 'c = list users logged in'
echo 'd = check system uptime'
echo

read choice
case $choice in 
a) date;;
b) ls;;
c) who;;
d) uptime;;
*) echo Invalid choice - BYE.
esac

